# Generated by Django 4.1 on 2022-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Exception')),
                ('string', models.TextField(default='No exception yet')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Navigation')),
                ('posX', models.FloatField(default=0.0)),
                ('posY', models.FloatField(default=0.0)),
                ('posZ', models.FloatField(default=0.0)),
                ('linVelX', models.FloatField(default=0.0)),
                ('linVelY', models.FloatField(default=0.0)),
                ('linVelZ', models.FloatField(default=0.0)),
                ('angVelX', models.FloatField(default=0.0)),
                ('angVelY', models.FloatField(default=0.0)),
                ('angVelZ', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RoverConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Science')),
                ('sc_text', models.TextField(null=True)),
                ('t1_hum', models.PositiveSmallIntegerField(null=True)),
                ('t2_hum', models.PositiveSmallIntegerField(null=True)),
                ('t3_hum', models.PositiveSmallIntegerField(null=True)),
                ('mass', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='TaskProgress')),
                ('state', models.PositiveSmallIntegerField(default=-1)),
            ],
        ),
    ]
