# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_no_ros/panel_object.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class panel_object(genpy.Message):
  _md5sum = "898cda956b9cf305c691a0c55e5ce854"
  _type = "vision_no_ros/panel_object"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8 id
int8 reliability
float32 x_pos
float32 y_pos
float32 z_pos
float32 x_rot
float32 y_rot
float32 z_rot
float32 w_quaternion
float32 x_quaternion
float32 y_quaternion
float32 z_quaternion
"""
  __slots__ = ['id','reliability','x_pos','y_pos','z_pos','x_rot','y_rot','z_rot','w_quaternion','x_quaternion','y_quaternion','z_quaternion']
  _slot_types = ['int8','int8','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,reliability,x_pos,y_pos,z_pos,x_rot,y_rot,z_rot,w_quaternion,x_quaternion,y_quaternion,z_quaternion

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(panel_object, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.reliability is None:
        self.reliability = 0
      if self.x_pos is None:
        self.x_pos = 0.
      if self.y_pos is None:
        self.y_pos = 0.
      if self.z_pos is None:
        self.z_pos = 0.
      if self.x_rot is None:
        self.x_rot = 0.
      if self.y_rot is None:
        self.y_rot = 0.
      if self.z_rot is None:
        self.z_rot = 0.
      if self.w_quaternion is None:
        self.w_quaternion = 0.
      if self.x_quaternion is None:
        self.x_quaternion = 0.
      if self.y_quaternion is None:
        self.y_quaternion = 0.
      if self.z_quaternion is None:
        self.z_quaternion = 0.
    else:
      self.id = 0
      self.reliability = 0
      self.x_pos = 0.
      self.y_pos = 0.
      self.z_pos = 0.
      self.x_rot = 0.
      self.y_rot = 0.
      self.z_rot = 0.
      self.w_quaternion = 0.
      self.x_quaternion = 0.
      self.y_quaternion = 0.
      self.z_quaternion = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2b10f().pack(_x.id, _x.reliability, _x.x_pos, _x.y_pos, _x.z_pos, _x.x_rot, _x.y_rot, _x.z_rot, _x.w_quaternion, _x.x_quaternion, _x.y_quaternion, _x.z_quaternion))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 42
      (_x.id, _x.reliability, _x.x_pos, _x.y_pos, _x.z_pos, _x.x_rot, _x.y_rot, _x.z_rot, _x.w_quaternion, _x.x_quaternion, _x.y_quaternion, _x.z_quaternion,) = _get_struct_2b10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2b10f().pack(_x.id, _x.reliability, _x.x_pos, _x.y_pos, _x.z_pos, _x.x_rot, _x.y_rot, _x.z_rot, _x.w_quaternion, _x.x_quaternion, _x.y_quaternion, _x.z_quaternion))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 42
      (_x.id, _x.reliability, _x.x_pos, _x.y_pos, _x.z_pos, _x.x_rot, _x.y_rot, _x.z_rot, _x.w_quaternion, _x.x_quaternion, _x.y_quaternion, _x.z_quaternion,) = _get_struct_2b10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b10f = None
def _get_struct_2b10f():
    global _struct_2b10f
    if _struct_2b10f is None:
        _struct_2b10f = struct.Struct("<2b10f")
    return _struct_2b10f
