// Generated by gencpp from file vision_no_ros/panel_object.msg
// DO NOT EDIT!


#ifndef VISION_NO_ROS_MESSAGE_PANEL_OBJECT_H
#define VISION_NO_ROS_MESSAGE_PANEL_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_no_ros
{
template <class ContainerAllocator>
struct panel_object_
{
  typedef panel_object_<ContainerAllocator> Type;

  panel_object_()
    : id(0)
    , reliability(0)
    , x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)
    , w_quaternion(0.0)
    , x_quaternion(0.0)
    , y_quaternion(0.0)
    , z_quaternion(0.0)  {
    }
  panel_object_(const ContainerAllocator& _alloc)
    : id(0)
    , reliability(0)
    , x_pos(0.0)
    , y_pos(0.0)
    , z_pos(0.0)
    , x_rot(0.0)
    , y_rot(0.0)
    , z_rot(0.0)
    , w_quaternion(0.0)
    , x_quaternion(0.0)
    , y_quaternion(0.0)
    , z_quaternion(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _reliability_type;
  _reliability_type reliability;

   typedef float _x_pos_type;
  _x_pos_type x_pos;

   typedef float _y_pos_type;
  _y_pos_type y_pos;

   typedef float _z_pos_type;
  _z_pos_type z_pos;

   typedef float _x_rot_type;
  _x_rot_type x_rot;

   typedef float _y_rot_type;
  _y_rot_type y_rot;

   typedef float _z_rot_type;
  _z_rot_type z_rot;

   typedef float _w_quaternion_type;
  _w_quaternion_type w_quaternion;

   typedef float _x_quaternion_type;
  _x_quaternion_type x_quaternion;

   typedef float _y_quaternion_type;
  _y_quaternion_type y_quaternion;

   typedef float _z_quaternion_type;
  _z_quaternion_type z_quaternion;





  typedef boost::shared_ptr< ::vision_no_ros::panel_object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_no_ros::panel_object_<ContainerAllocator> const> ConstPtr;

}; // struct panel_object_

typedef ::vision_no_ros::panel_object_<std::allocator<void> > panel_object;

typedef boost::shared_ptr< ::vision_no_ros::panel_object > panel_objectPtr;
typedef boost::shared_ptr< ::vision_no_ros::panel_object const> panel_objectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_no_ros::panel_object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_no_ros::panel_object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision_no_ros::panel_object_<ContainerAllocator1> & lhs, const ::vision_no_ros::panel_object_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.reliability == rhs.reliability &&
    lhs.x_pos == rhs.x_pos &&
    lhs.y_pos == rhs.y_pos &&
    lhs.z_pos == rhs.z_pos &&
    lhs.x_rot == rhs.x_rot &&
    lhs.y_rot == rhs.y_rot &&
    lhs.z_rot == rhs.z_rot &&
    lhs.w_quaternion == rhs.w_quaternion &&
    lhs.x_quaternion == rhs.x_quaternion &&
    lhs.y_quaternion == rhs.y_quaternion &&
    lhs.z_quaternion == rhs.z_quaternion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision_no_ros::panel_object_<ContainerAllocator1> & lhs, const ::vision_no_ros::panel_object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision_no_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision_no_ros::panel_object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_no_ros::panel_object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_no_ros::panel_object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_no_ros::panel_object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_no_ros::panel_object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_no_ros::panel_object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_no_ros::panel_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "898cda956b9cf305c691a0c55e5ce854";
  }

  static const char* value(const ::vision_no_ros::panel_object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x898cda956b9cf305ULL;
  static const uint64_t static_value2 = 0xc691a0c55e5ce854ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_no_ros::panel_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_no_ros/panel_object";
  }

  static const char* value(const ::vision_no_ros::panel_object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_no_ros::panel_object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n"
"int8 reliability\n"
"float32 x_pos\n"
"float32 y_pos\n"
"float32 z_pos\n"
"float32 x_rot\n"
"float32 y_rot\n"
"float32 z_rot\n"
"float32 w_quaternion\n"
"float32 x_quaternion\n"
"float32 y_quaternion\n"
"float32 z_quaternion\n"
;
  }

  static const char* value(const ::vision_no_ros::panel_object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_no_ros::panel_object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.reliability);
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.z_pos);
      stream.next(m.x_rot);
      stream.next(m.y_rot);
      stream.next(m.z_rot);
      stream.next(m.w_quaternion);
      stream.next(m.x_quaternion);
      stream.next(m.y_quaternion);
      stream.next(m.z_quaternion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct panel_object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_no_ros::panel_object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_no_ros::panel_object_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "reliability: ";
    Printer<int8_t>::stream(s, indent + "  ", v.reliability);
    s << indent << "x_pos: ";
    Printer<float>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<float>::stream(s, indent + "  ", v.y_pos);
    s << indent << "z_pos: ";
    Printer<float>::stream(s, indent + "  ", v.z_pos);
    s << indent << "x_rot: ";
    Printer<float>::stream(s, indent + "  ", v.x_rot);
    s << indent << "y_rot: ";
    Printer<float>::stream(s, indent + "  ", v.y_rot);
    s << indent << "z_rot: ";
    Printer<float>::stream(s, indent + "  ", v.z_rot);
    s << indent << "w_quaternion: ";
    Printer<float>::stream(s, indent + "  ", v.w_quaternion);
    s << indent << "x_quaternion: ";
    Printer<float>::stream(s, indent + "  ", v.x_quaternion);
    s << indent << "y_quaternion: ";
    Printer<float>::stream(s, indent + "  ", v.y_quaternion);
    s << indent << "z_quaternion: ";
    Printer<float>::stream(s, indent + "  ", v.z_quaternion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_NO_ROS_MESSAGE_PANEL_OBJECT_H
