# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msg_python/move_base_action_goal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class move_base_action_goal(genpy.Message):
  _md5sum = "512860f1cd6d90bb8cf7bd87927bb3d7"
  _type = "custom_msg_python/move_base_action_goal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """
std_msgs/Int8 currId
geometry_msgs/Pose moveBaseGoal

================================================================================
MSG: std_msgs/Int8
int8 data

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['currId','moveBaseGoal']
  _slot_types = ['std_msgs/Int8','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       currId,moveBaseGoal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(move_base_action_goal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.currId is None:
        self.currId = std_msgs.msg.Int8()
      if self.moveBaseGoal is None:
        self.moveBaseGoal = geometry_msgs.msg.Pose()
    else:
      self.currId = std_msgs.msg.Int8()
      self.moveBaseGoal = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b7d().pack(_x.currId.data, _x.moveBaseGoal.position.x, _x.moveBaseGoal.position.y, _x.moveBaseGoal.position.z, _x.moveBaseGoal.orientation.x, _x.moveBaseGoal.orientation.y, _x.moveBaseGoal.orientation.z, _x.moveBaseGoal.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currId is None:
        self.currId = std_msgs.msg.Int8()
      if self.moveBaseGoal is None:
        self.moveBaseGoal = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.currId.data, _x.moveBaseGoal.position.x, _x.moveBaseGoal.position.y, _x.moveBaseGoal.position.z, _x.moveBaseGoal.orientation.x, _x.moveBaseGoal.orientation.y, _x.moveBaseGoal.orientation.z, _x.moveBaseGoal.orientation.w,) = _get_struct_b7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b7d().pack(_x.currId.data, _x.moveBaseGoal.position.x, _x.moveBaseGoal.position.y, _x.moveBaseGoal.position.z, _x.moveBaseGoal.orientation.x, _x.moveBaseGoal.orientation.y, _x.moveBaseGoal.orientation.z, _x.moveBaseGoal.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currId is None:
        self.currId = std_msgs.msg.Int8()
      if self.moveBaseGoal is None:
        self.moveBaseGoal = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.currId.data, _x.moveBaseGoal.position.x, _x.moveBaseGoal.position.y, _x.moveBaseGoal.position.z, _x.moveBaseGoal.orientation.x, _x.moveBaseGoal.orientation.y, _x.moveBaseGoal.orientation.z, _x.moveBaseGoal.orientation.w,) = _get_struct_b7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b7d = None
def _get_struct_b7d():
    global _struct_b7d
    if _struct_b7d is None:
        _struct_b7d = struct.Struct("<b7d")
    return _struct_b7d
