# Generated by Django 3.2.9 on 2022-03-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0003_navigation_posx'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='posY',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
