# Generated by Django 3.2.9 on 2022-03-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0004_navigation_posy'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='linAngX',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='linAngY',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='linAngZ',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='linVelX',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='linVelY',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='linVelZ',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='posZ',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
