# Generated by Django 3.2.9 on 2022-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0005_auto_20220322_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='mass',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science',
            name='t1_hum',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science',
            name='t2_hum',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='science',
            name='t3_hum',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
