# Generated by Django 3.2.9 on 2022-03-22 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0006_auto_20220322_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='linAngX',
            new_name='angVelX',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='linAngY',
            new_name='angVelY',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='linAngZ',
            new_name='angVelZ',
        ),
    ]
