# Generated by Django 3.2.9 on 2022-03-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0007_auto_20220322_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='roverconfirmation',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
