# Generated by Django 3.2.9 on 2022-03-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0008_roverconfirmation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='name',
            field=models.TextField(default='Exception'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='name',
            field=models.TextField(default='Navigation'),
        ),
        migrations.AddField(
            model_name='science',
            name='name',
            field=models.TextField(default='Science'),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='name',
            field=models.TextField(default='TaskProgress'),
        ),
        migrations.AlterField(
            model_name='roverconfirmation',
            name='name',
            field=models.TextField(default='False'),
        ),
    ]
