# Generated by Django 3.2.9 on 2022-03-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0009_auto_20220331_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='string',
            field=models.TextField(default='No exception yet'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='angVelX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='angVelY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='angVelZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='linVelX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='linVelY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='linVelZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='posX',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='posY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='posZ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='roverconfirmation',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='science',
            name='mass',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='science',
            name='sc_text',
            field=models.TextField(default='Nothing yet.'),
        ),
        migrations.AlterField(
            model_name='science',
            name='t1_hum',
            field=models.PositiveSmallIntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='science',
            name='t2_hum',
            field=models.PositiveSmallIntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='science',
            name='t3_hum',
            field=models.PositiveSmallIntegerField(default='-1'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='state',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
    ]
