# Generated by Django 3.2.9 on 2022-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0010_auto_20220331_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='mass',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='science',
            name='t1_hum',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='science',
            name='t2_hum',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='science',
            name='t3_hum',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
    ]
