# Generated by Django 3.2.9 on 2022-04-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0011_auto_20220401_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverconfirmation',
            name='name',
            field=models.TextField(default='RoverConfirm'),
        ),
    ]
