# Generated by Django 3.2.9 on 2022-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0012_alter_roverconfirmation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.TextField(default='Science', editable=False),
        ),
    ]
