# Generated by Django 3.2.9 on 2022-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0013_alter_science_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverconfirmation',
            name='name',
            field=models.TextField(),
        ),
    ]
