# Generated by Django 3.2.9 on 2022-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0014_alter_roverconfirmation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='sc_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='t1_hum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='t2_hum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='science',
            name='t3_hum',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
