# Generated by Django 3.2.9 on 2022-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Xplore_CS_2022', '0015_auto_20220403_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='name',
            field=models.TextField(default='Science'),
        ),
    ]
