BUTTONS:
  TRIANGLE: triangle
  SQUARE: square
  CIRCLE: circle
  CROSS: cross
  L1: L1
  R1: R1
  L3: L3
  R3: R3
  CREATE: create
  OPTIONS: options
  PS: PS
  TOUCHPAD: touchpad

ANALOG_TRIGGERS:
  RH: RH
  RV: RV
  LH: LH
  LV: LV
  L2: L2
  R2: R2
  DIRH: dirH
  DIRV: dirV

DEFAULT_IDS:
  TRIANGLE: 307
  SQUARE: 308
  CIRCLE: 305
  CROSS: 304
  L1: 310
  R1: 311
  L2: 2
  R2: 5
  PS: 316
  LH: 0
  LV: 1
  RH: 3
  RV: 4
  DIRH: 16
  DIRV: 17
  CREATE: 312
  OPTIONS: 313
